Ghostobot
DipProject-org/ParserFreelanser2 pull request #1
Opened 2018-10-15 09:03 UTC by Abigile

2018-10-16 16:52 UTC, TovarischSukhov requested changes

2018-10-16 16:52 UTC, TovarischSukhov commented on lanser_bot.py
> +			update.message.reply_text('\nЗадание: {0}\nОплата:{4}{5}\nАктивно еще {1}.\n\nОписание: {2}\n\nТребуемые навыки{3}\n\nПредложений от фрилансеров:{6}\n\nСтраница заказа:  {4}\n\n'.format(card['titl
1. строки лучше вывести в message_texts.py
```
PAY_STATUS_MESSAGE = '\nЗадание: {0}\nОплата:{4}{5}\nАктивно еще {1}.\n\nОписание: {2}\n\nТребуемые навыки{3}\n\nПредложений от фрилансеров:{6}\n\nСтраница заказа:  {4}\n\n' 
```

в этом файле делаешь импорт, а потом``` PAY_STATUS_MESSAGE.format(...)```

2. лучше осознанно именовать аргументы:
```
'Задание: {task}'.format(task='123445')
```

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_main.py
> +import requests
слова в названии файлов разделяй ```_```, то есть ```skills_list_main``` так читать проще

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_main.py
> +	main()
пустую строку в конце файла ннада

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_main.py
> +	print('Запуск')
принты замени на логирование. Плюс - его можно направлять и в консоль и в файл и если что-то упадет, логи останутся, а принты пропадут

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_main.py
> +	return r.text
а если текста не будет? или тебе вернется не 200, а 404, например и в тексте будет "не найдено"?

2018-10-16 16:52 UTC, TovarischSukhov commented on .gitignore
>  proxies.txt
скинешь в личку, я гляну структуру, может можно лучше, чтоб парсить его проще было

2018-10-16 16:52 UTC, TovarischSukhov commented on .gitignore
> +Desktop.ini
пустая строка в конце файла

2018-10-16 16:52 UTC, TovarischSukhov commented on lanser_bot.py
> +from telegram import ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove, InlineKeyboardMarkup, InlineKeyboardButton
длинные импорты оформляются через скобочки 
```
from telegram import (
    ReplyKeyboardMarkup, KeyboardButton,
    ReplyKeyboardRemove, InlineKeyboardMarkup,
)
```

2018-10-16 16:52 UTC, TovarischSukhov commented on lanser_bot.py
предлагаю сделать класс SomeBot, у которого будут функции talk_to_me , greet_user и все, что относится к разговору с клиентом

2018-10-16 16:52 UTC, TovarischSukhov commented on lanser_bot.py
>  def zapros_start(bot, update, user_data):
лучше на англ переводить, гугл транслейт в помощь

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_main.py
> +	print('Запуск')
а если это отладочные - то logger.gebug нужен

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_find_links.py
> +	db_session.commit()
пустая строка =)

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_main.py
> +def main():
все, что до этого лучше убрать, в мейн обычно лежит только запуск программы
мейн должен лежать в корневой папке (главной)

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_main.py
> +def get_proxy():
вынести отдельный блок - папка external_connections
в файл utils.py - получение прокси
в файл freelance_connector.py - хождение по урлу

дальше комментировать эти функции буду, как разнесешь)

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_find_links.py
> +from bs4 import BeautifulSoup
я бы сделала отдельную папочку fill_db или что-то вроде
в которой был бы мейн, запускающий наливку базы
и файл praser.py

2018-10-16 16:52 UTC, TovarischSukhov commented on skilllist_find_links.py
> +		link = block.get('href')
все, что ниже выделить в отдельную функцию и ее вызывать

2018-10-18 00:39 UTC, Abigile commented on skilllist_main.py
> +	return r.text
Функция вызывается внутри конструкции:
while True:
try:
html = get html()
break
except request.exceptions.RequestExceptions as e:
logging.info(e)
Таким же образом запрашиваются и листы со списком карточек-заказов.

2018-10-19 22:27 UTC, TovarischSukhov requested changes

2018-10-19 22:27 UTC, TovarischSukhov commented on message_texts.py
> +CORRECTOR = 'Может быть вы имели ввиду {}'
пустая срока =)\

2018-10-19 22:27 UTC, TovarischSukhov commented on .gitignore
> +
можно добавить гитигнор в гитигнор, чтобы не палить локальные файлы =)

2018-10-19 22:27 UTC, TovarischSukhov commented on bot/talk_with_user.py
> +from utils import get_five_cards
сначала импорты из стандартных библиотек, потом из локальных файлов

2018-10-19 22:27 UTC, TovarischSukhov commented on bot/talk_with_user.py
> +def query_to_base_start(bot, update, user_data):
Это надо убрать в ```db_connections -> connection.py```
```class DataBaseSelector()```
В ините коннектишься
дальше функции а-ля ```find_skill_by_name():``` которые ты и будешь использовать

то есть тут ты просто импортируешь ```DataBaseSelector```, инитишь его (```db_selector = DataBaseSelector()```)
а потом ```db_selector.find_skill_by_name(name)```

2018-10-19 22:27 UTC, TovarischSukhov commented on bot/talk_with_user.py
> +def query_to_base_get_skill(bot, update, user_data):
тоже функцией к ```DataBaseSelector```

2018-10-19 22:27 UTC, TovarischSukhov commented on bot/talk_with_user.py
> +def query_to_base_start(bot, update, user_data):
то есть запросы к базе ты убираешь туда
а тут оставляешь класс ```SkillBot()```
у которого методы ```answer_by_skill```  итд (названия сам придумай, я пока не во все строчки вчиталась)

2018-10-19 22:27 UTC, TovarischSukhov commented on bot/talk_with_user.py
> +		return 'skill'
пустая строка =)

2018-10-19 22:27 UTC, TovarischSukhov commented on Прототипы под api/getall_sql.py
> +from sqlalchemy import create_engine, Column, Integer, String, Text
про кириллицу в названиях файлов и папок - забудь!

2018-10-19 22:27 UTC, TovarischSukhov commented on Прототипы под api/getall_sql.py
> +from sqlalchemy import create_engine, Column, Integer, String, Text
этот файл хорошая наметка к тому, что я выше писала про работу с базой
только переименуй чтоб понятно было и перетащи методы =)

2018-10-19 22:27 UTC, TovarischSukhov commented on Прототипы под api/getall_sql.py
> +		self.skill=skill
скилл вс-таки наверное не в ините должен быть, ты ж по нему ищешь, он постоянно меняется
а в класск лучше хранить что-то что ты хочешь сохранить между вызовами функций

2018-10-19 22:27 UTC, TovarischSukhov commented on Прототипы под api/getall_sql.py
> +		self.skill=skill
если я вообще правильно поняла, что ты тут хотел сделать...

2018-10-25 06:15 UTC, TovarischSukhov commented on bot/talk_with_user.py
> +	if not os.path.exists("skillbase.db"):
эту штуку лучше прогонять 1 раз при старте бота

2018-10-25 06:15 UTC, TovarischSukhov commented on bot/talk_with_user.py
> +	text = START.format(update.message.chat.first_name)
а если имени нет в телеге?

2018-10-28 19:06 UTC, TovarischSukhov requested changes

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +	proxies = get_proxy()
по названию функции кажется, что вернется 1 прокся

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +def get_five_cards(link):
я бы сделала get_cads
а количество карточек бы вынесла в переменную окружения или явно передавала параметром

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +def find_works_card(html):		#получаем ссылку, число работ
соответственно тут у тебя будет параметр с количеством требуемых карточек

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +	if need_login == True:
можно просто ```if need_login:```

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +	if featured == False and need_login == False:
достаточно ```elif not featured:```

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +def parser(block):
это функция, их глаголами называют, лучше ```parse```

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +	if featured == True:
это else от предыдущего условия? или тут все равно на need_login?

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +		description = 'Need Login for description'
может сразу формировать карточку и возвращать?

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +	card = {'title':title, 'time':time, 'description':description, 'list_skill':list_skill, 'link':link, 'price':price, 'verified':verified, 'bids':bids}
лучше в отдельную функцию 
```
def serialize_card(**kwargs):
    return {
'title':title,
 'time':time,
 'description':description, 
'list_skill':list_skill, 
'link':link, 
'price':price,
 'verified':verified,
 'bids':bids
}
```

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +	return card
и тут тогда ```return serialize_card(...)```

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +		bids = '0'
и тут я бы тоже сразу возвращала

2018-10-28 19:06 UTC, TovarischSukhov commented on utils.py
> +	title = title.replace('  ','')
вынеси в функцию ```normalize_str```
и в ней все возможные реплейсы 

а потом везде 
```
title = normalize_str(block.find('a', class_='JobSearchCard-primary-heading-link').contents[0])
...
description = normalize_str(block.find('p', class_='JobSearchCard-primary-description').contents[0])
```

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +
последняя строка должна быть пустая, без отступов =)

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +	regexp= r'^/jobs/'
давай как-нибудь человекочитаемо, например jobs_prefix или что-то вроде

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +	db_session.query(Skillbase).delete()
Oo а точно все удаляем?

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +		skill_words = title_str.replace('(','')
все реплейсы либо в регексп либо в отдельную функцию (ниже описала)

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +			skill_words = skill_words.remove(' ')
а не проще убрать повторяющиеся пробелы заранее?

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +		str3 = str3.split('\xa0')
попробуй ```words_only = ' '.join(string.split())``` <- эта штука оставит тебе только слова через пробелы

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +			skill_words.append((title_str).lower())
ты ж ее потом как str3 меняешь, но не используешь

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +		db_session.add(skill_db)
работу с базой надо отдельно проводить

делаешь файл models.py
в нем описываешь модель
у модели делаешь метод add_skill
в нем коннектишься ,добавляешь и коммитишь

тут просто импортируешь ```from models import Skill```
Skill.add_skill(данные)

2018-10-28 19:06 UTC, TovarischSukhov commented on setup_db/create_db.py
> +	while True: #Повторяй цикл до ответа от прокси сервера
выбор прокси убери внутрь ```get_proxy()```
а если будет дальше при запросе проверяй на ошибки 403 или таймауты
если что-то из них еще раз ```get_proxy()```

2018-10-28 19:06 UTC, TovarischSukhov commented on external_connections/connections_utils.py
> +	r = requests.get(url, proxies = proxy)
тут лучше проверять ответ сразу
ловить надо 404, 403, 500 и таймауты
нормальный код ответа 200 - с ним ты возвращаешь текст (проверяя, что он есть и не пустой)

2018-10-28 19:06 UTC, TovarischSukhov commented on db_connections/connections.py
> +class DataBaseSelector():
это лучше в модель превратить (ниже описала как)

2018-10-30 07:42 UTC, Abigile commented on utils.py
> +	if featured == True:
На need_login здесь все равно)
featured и need_login встречаются как вместе, так и врозь. 
Там идут неполные данные на карточку и поэтому при их наличии бот корректирует карту.

2018-10-30 13:44 UTC, Abigile commented on setup_db/skill_list_find_links.py
> +	db_session.query(Skillbase).delete()
Да)Все) Здесь мы заполняем таблицу навыков. 
Это делается только в том случае, если файла базы нет
или он некорректно создался 
или устарел настолько, что содержит неполную базу.
Т.е. случаи - разовый, в которм нужно переписывать всю базу.

2018-10-31 06:20 UTC, Abigile commented on setup_db/skill_list_find_links.py
> +		skill_words = title_str.replace('(','')
Не понимаю))
def find_links(html) парсит страницу и извлекает  по 4 значения с 490 блоков.
Код для каждого из 4-х извлечений - не повторяется более нигде по программе.
Можно каждое извлечение выделить в отдельную функцию.  Так и сделать? (По принципу одно действие - одна функция)

2018-10-31 11:44 UTC, TovarischSukhov commented on setup_db/skill_list_find_links.py
> +		skill_words = title_str.replace('(','')
ненене
я не про код парсилки
```some_str.replace('(','')``` <- у тебя таких выражений много разных, они все написаны по отдельности
наверное, имеет смысл сделать функцию "очищающую" строку от знаков препинания, двойных пробелов итд
и вызывать ее везде
внутри этой функции может быть 1 регексп, оставляющий только слова плюс
 ```' '.join(some_str.split(())``` <- уберет повторы пробелов

2018-10-31 11:48 UTC, Abigile commented on setup_db/skill_list_find_links.py
> +		db_session.add(skill_db)
что такое модель?  класс, к-й отдельно записывает и комитит каждую из 490 записей?

2018-10-31 13:30 UTC, Abigile commented on setup_db/create_db.py
> +	while True: #Повторяй цикл до ответа от прокси сервера
get_proxy - разовая функция создания/получения доступа  к списку прокси
get_proxy - переименовать в load_proxy
возможно лучше выбор прокси переместить в новую функцию use_proxy из которой вызывать load_proxy

2018-11-10 01:54 UTC, merged